name: Deploy to Stage
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  deploy:
    env:
      NAMESPACE: stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Dependencies CDK
        run: npm install -g aws-cdk
        working-directory: ./testeRepositorio
      
      - name: Install Dependencies
        run: npm install
        working-directory: ./testeRepositorio

      - name: Run Lambda Tests
        run: npm run test
        working-directory: ./testeRepositorio/lambda

      - name: Deploy CDK
        run: cdk deploy --require-approval never
        working-directory: ./testeRepositorio